version: '3.1'

services:
  #  db:
  #    container_name: db_postgres
  #    image: postgres
  #    restart: always
  #    ports:
  #      - 5432:5432
  #    environment:
  #      POSTGRES_PASSWORD: example
  server:
    container_name: server
    build: .
    ports:
      - 8080:8080

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CI=true
    stdin_open: true

networks:
  default:
    driver: bridge