version: '3.1'

services:
  server:
    container_name: server
    build: .
    ports:
      - 8080:8080

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CI=true
    stdin_open: true

networks:
  default:
    driver: bridge